### ISSUE TITLE
How can i add multiple tables(with different structures) in 1 csv file?

### ISSUE THREAD

**Issue by Shruti2208** [vigneshuvi/SwiftCSVExport#19]
I want to have 1 csv file with 3 different tables for my MacOS project which i'm building using swift 5.
Please guide

**Comment by vigneshuvi** [comment]
@Shruti2208 , Why you want merge three tables into one CSV file?

```
Tables Example:
Teacher(id,name), Student(id,name), School(id,name)

Do you want merge like in below CSV format?
Teacher_id, Teacher_name, Student_id, Student_name,School_id,School_name
```

Do you have any real samples/examples?

**Comment by Shruti2208** [comment]
I do not wish to merge the tables.
There are 3 separate tables in 1 screen.
I want to export all of those in 1 csv file as individual tables.

**Comment by vigneshuvi** [comment]
@Shruti2208 , Please provide some examples like which i gave above?

**Comment by Shruti2208** [comment]
![Screenshot 2020-03-12 at 12 04 37 PM](https://user-images.githubusercontent.com/60172172/76493870-aae19980-6459-11ea-84b3-8b08197b2e11.png)

Attached is the screenshot of the view i want to convert into csv.

**Comment by vigneshuvi** [comment]
@Shruti2208 , Below there tables right? Are you using swift?

**Comment by Shruti2208** [comment]
Yes i want to export the tables displayed in the bottom section into 1 CSV file, I'm using Swift.

**Comment by vigneshuvi** [comment]
@Shruti2208 , 
As of now, I assuming only merge options available from because CSV is basically column and row concept.

We have to provide the column name(You have maintain the order) in first row and values should in the row.

Example:

`Total Sale IN GBP, USD, Total Sale In INR, MARGIN, JOB, ELECTRICITY, EXTRA MISC, EXTRA ELEC, EXTRA DIESEL, GST Refund, EXTRA, Interest, Payment, Extra Profit`


Other Option is Key - Value pair: 

```
Column-Name, Value
Total Sale IN GB, 480
USD,76
```

**Comment by Shruti2208** [comment]
Ok, thanks for your time. I was successful to export 1 table.
I will have to consider other options like exporting to excel file.

**Comment by vigneshuvi** [comment]
Closed
