### ISSUE TITLE
Using ; as divider

### ISSUE THREAD

**Issue by macshodan** [vigneshuvi/SwiftCSVExport#7]
Hi, first of all thanks for your amazing work.

I only have one problem, I cannot set the field divider to semicolon (;) instead of commas.

I've tried: 
```
  let writeCSVObj = CSV()
  writeCSVObj.delimiter = DividerType.semicolon.rawValue
  writeCSVObj.rows = data
  writeCSVObj.fields = headers as NSArray
  writeCSVObj.name = "ExportTest"
```

as well as:

```
  let writeCSVObj = CSV()
  writeCSVObj.delimiter = ";"
  writeCSVObj.rows = data
  writeCSVObj.fields = headers as NSArray
  writeCSVObj.name = "ExportTest"
```
but the output file will always have commas as field dividers. Am I missing something?

**Comment by vigneshuvi** [comment]
@macshodan, Thanks for reporting this issue.

I've fixed this issue. you can download the latest version of SwiftCSVExport framework version [2.0.0](https://github.com/vigneshuvi/SwiftCSVExport/releases/tag/2.0.0).


` writeCSVObj.delimiter = DividerType.semicolon.rawValue`


Try to download like this if you are not able to download latest version. 

pod 'SwiftCSVExport', :git => 'https://github.com/vigneshuvi/SwiftCSVExport.git', :tag => '2.0.0'

or 

try 'pod update' instead of 'pod install' in terminal.

Example code was updated [here!](
https://github.com/vigneshuvi/SwiftCSVExport/blob/master/Examples/SampleSwift/SampleSwift/ViewController.swift#L69-L80)
